### ISSUE TITLE
bug nell'implementazione di max flow min sus of amogus decomposition

### ISSUE THREAD

**Issue by MarcoPellero** [MatteoArcari/Terry-Algos#1]
quando giro il tuo programma per fossili che scompone i numeri in crewmate per eseguirci un max flow min sus mi crasha il programma: `SIGSUS signal received; dumped core; vented 😳 `

**Comment by MatteoArcari** [comment]
Ok si fixo appena finisco di implementare il treap di convex hull con index compressione per fare trova la parità con in O(1/log(pi/e))

**Comment by MarcoPellero** [comment]
O(1/log(pi/e)) è O(1) comunque

**Comment by roccopp** [comment]
implementazione dell'algoritmo per i divisori primi errata (skill issue)

**Comment by MatteoArcari** [comment]
true issue. fixing
